server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitlab.com/zhengyulin19960415/spring-cloud-config.git
          search-paths: respo
          username: zhengyulin19960415
          password: zyl690408564
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/